In [1]:
import numpy as np

In [2]:
np.__version__

'2.3.5'

In [3]:
my_list= [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [4]:
arr = np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [5]:
print(type(my_list))
print(type(arr))

<class 'list'>
<class 'numpy.ndarray'>


In [6]:
np.arange(10) # return array with value 0 to 9

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(10,20) # range from 10 to 19

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [8]:
np.arange(10,50,5) # range of 10 t0 50 step by 5

array([10, 15, 20, 25, 30, 35, 40, 45])

In [9]:
np.arange(20,10)

array([], dtype=int64)

In [10]:
np.arange(-20,10) # first argument is less that second argument

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [11]:
np.zeros(3)#1d array -  parameter tunning

array([0., 0., 0.])

In [12]:
np.zeros(3,dtype=int) # hyperparameter tunning, return int array

array([0, 0, 0])

In [13]:
np.zeros([2,2]) # 2D array, with value 0.0 (float)

array([[0., 0.],
       [0., 0.]])

In [14]:
np.zeros([2,2], dtype = int) # 2D array with int value as 0 

array([[0, 0],
       [0, 0]])

In [15]:
np.zeros([10,10]) # nd array

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [16]:
np.ones(4) # 1d with values as 1's float

array([1., 1., 1., 1.])

In [17]:
np.ones(4,dtype=int) # 1d with values as 1's int velues

array([1, 1, 1, 1])

In [18]:
np.random.rand(3) # generates 3 random numbers

array([0.44966837, 0.38288629, 0.73814152])

In [19]:
np.random.rand(3,4) # generates 3 random numbers

array([[0.71553386, 0.70745387, 0.27718984, 0.35876176],
       [0.5923956 , 0.175453  , 0.8644854 , 0.8695018 ],
       [0.89995238, 0.03130264, 0.42372484, 0.23145462]])

In [20]:
np.random.randint(3) # generates a random number from 0 to 3
# randint(low, high=None, size=None, dtype=int)

1

In [21]:
for i in range(10):
    rnumb = np.random.randint(10, 20,dtype=int)
    print(rnumb)

18
13
12
11
13
13
16
17
14
12


In [22]:
print(np.random.randint(1,10,4))

[6 2 9 6]


In [23]:
m = np.random.randint(1,10,(4,6)) # (4,6)4 rows, 6 columns, and values ranging from 1 to 10.
print(m)

[[5 2 2 5 9 2]
 [8 8 9 8 9 7]
 [4 2 5 5 5 9]
 [4 4 4 7 4 6]]


In [24]:
# indexing and slicing in array

In [25]:
print(m)

[[5 2 2 5 9 2]
 [8 8 9 8 9 7]
 [4 2 5 5 5 9]
 [4 4 4 7 4 6]]


In [26]:
m[0] # return the first row.

array([5, 2, 2, 5, 9, 2])

In [27]:
m[0] = [2,4,6,8,9,3] # array manuplation, updating the value of 1st row.
print(m)

[[2 4 6 8 9 3]
 [8 8 9 8 9 7]
 [4 2 5 5 5 9]
 [4 4 4 7 4 6]]


In [28]:
m[2] # index always start form 0, 2 is 3rd row

array([4, 2, 5, 5, 5, 9])

In [29]:
m[-3] # from backward, -1 is last element, -2 is previous to last and -3 is the second before first, -4 is the first row

array([8, 8, 9, 8, 9, 7])

In [30]:
print(m[0,4]) # printing specific value from 0th row, value at index 4.

9


In [31]:
print(m[-2,-3])

5
