# numpy: part 2


In [151]:
import numpy as np

In [175]:
m = np.random.randint(1,10,(4,6)) # (4,6)4 rows, 6 columns, and values ranging from 1 to 10.
print(m)


[[4 2 6 9 9 1]
 [2 4 2 6 1 2]
 [9 5 4 5 7 4]
 [2 3 5 7 4 4]]


In [177]:
print(m[1:4,1:3])
print(len(m))
print(m[2:4,3:6])


[[4 2]
 [5 4]
 [3 5]]
4
[[5 7 4]
 [7 4 4]]


In [154]:
m

array([[7, 8, 7, 7, 2, 9],
       [5, 6, 1, 3, 2, 2],
       [4, 8, 3, 8, 4, 8],
       [1, 4, 1, 3, 1, 8]])

In [173]:
m[:]

array([[4, 3, 2, 6, 3, 8, 6, 8, 1],
       [3, 8, 5, 3, 3, 3, 8, 1, 9],
       [5, 4, 7, 3, 6, 2, 8, 9, 3],
       [9, 8, 4, 4, 7, 8, 7, 8, 2],
       [2, 8, 8, 5, 7, 7, 8, 1, 9],
       [8, 2, 7, 3, 8, 7, 9, 7, 4],
       [7, 2, 7, 4, 5, 3, 2, 9, 5],
       [1, 8, 8, 6, 6, 3, 2, 1, 9],
       [1, 3, 5, 7, 3, 7, 3, 4, 4]])

In [156]:

m.shape
m[1:3,1:3]

array([[6, 1],
       [8, 3]])

In [157]:
m[2]


array([4, 8, 3, 8, 4, 8])

In [158]:
# m[:,0]
m

array([[7, 8, 7, 7, 2, 9],
       [5, 6, 1, 3, 2, 2],
       [4, 8, 3, 8, 4, 8],
       [1, 4, 1, 3, 1, 8]])

In [159]:
m[:,0] 

array([7, 5, 4, 1])

In [160]:
m1 = m = np.random.randint(1,10,(9,9))
m1

array([[4, 3, 2, 6, 3, 8, 6, 8, 1],
       [3, 8, 5, 3, 3, 3, 8, 1, 9],
       [5, 4, 7, 3, 6, 2, 8, 9, 3],
       [9, 8, 4, 4, 7, 8, 7, 8, 2],
       [2, 8, 8, 5, 7, 7, 8, 1, 9],
       [8, 2, 7, 3, 8, 7, 9, 7, 4],
       [7, 2, 7, 4, 5, 3, 2, 9, 5],
       [1, 8, 8, 6, 6, 3, 2, 1, 9],
       [1, 3, 5, 7, 3, 7, 3, 4, 4]])

In [161]:
m1[0:9:3] # from 0 to 9 but step slice it by 3 

array([[4, 3, 2, 6, 3, 8, 6, 8, 1],
       [9, 8, 4, 4, 7, 8, 7, 8, 2],
       [7, 2, 7, 4, 5, 3, 2, 9, 5]])

In [162]:
m1[::2]

array([[4, 3, 2, 6, 3, 8, 6, 8, 1],
       [5, 4, 7, 3, 6, 2, 8, 9, 3],
       [2, 8, 8, 5, 7, 7, 8, 1, 9],
       [7, 2, 7, 4, 5, 3, 2, 9, 5],
       [1, 3, 5, 7, 3, 7, 3, 4, 4]])

In [163]:
m1[::5]

array([[4, 3, 2, 6, 3, 8, 6, 8, 1],
       [8, 2, 7, 3, 8, 7, 9, 7, 4]])

In [164]:
m1[::-1]

array([[1, 3, 5, 7, 3, 7, 3, 4, 4],
       [1, 8, 8, 6, 6, 3, 2, 1, 9],
       [7, 2, 7, 4, 5, 3, 2, 9, 5],
       [8, 2, 7, 3, 8, 7, 9, 7, 4],
       [2, 8, 8, 5, 7, 7, 8, 1, 9],
       [9, 8, 4, 4, 7, 8, 7, 8, 2],
       [5, 4, 7, 3, 6, 2, 8, 9, 3],
       [3, 8, 5, 3, 3, 3, 8, 1, 9],
       [4, 3, 2, 6, 3, 8, 6, 8, 1]])

In [165]:
m1[-1]# reversed only th efirst row

array([1, 3, 5, 7, 3, 7, 3, 4, 4])

In [166]:
m

array([[4, 3, 2, 6, 3, 8, 6, 8, 1],
       [3, 8, 5, 3, 3, 3, 8, 1, 9],
       [5, 4, 7, 3, 6, 2, 8, 9, 3],
       [9, 8, 4, 4, 7, 8, 7, 8, 2],
       [2, 8, 8, 5, 7, 7, 8, 1, 9],
       [8, 2, 7, 3, 8, 7, 9, 7, 4],
       [7, 2, 7, 4, 5, 3, 2, 9, 5],
       [1, 8, 8, 6, 6, 3, 2, 1, 9],
       [1, 3, 5, 7, 3, 7, 3, 4, 4]])

In [167]:
m[::-4]

array([[1, 3, 5, 7, 3, 7, 3, 4, 4],
       [2, 8, 8, 5, 7, 7, 8, 1, 9],
       [4, 3, 2, 6, 3, 8, 6, 8, 1]])

In [168]:
my_list= [0,1,2,3,4,5]
arr = np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [169]:
arr.shape

(6,)

In [170]:
m1.shape # 


(9, 9)

In [171]:
m1.reshape(6,6) # reshaping should match with the original number of elements already in the beginning

ValueError: cannot reshape array of size 81 into shape (6,6)

In [ ]:
m2 = np.random.randint(1,10,(2,3))

In [ ]:
m2.shape

(2, 3)

In [ ]:
m2

array([[2, 9, 2],
       [9, 8, 6]])

In [ ]:
m2.reshape(6,1) # since the number are matching it will reshape the matrix.

array([[2],
       [9],
       [2],
       [9],
       [8],
       [6]])

In [ ]:
m1

array([[1, 3, 7, 1, 5, 5, 5, 2, 1],
       [4, 7, 7, 3, 8, 3, 7, 1, 7],
       [2, 8, 4, 6, 7, 2, 5, 9, 6],
       [1, 3, 5, 4, 3, 6, 9, 8, 7],
       [9, 3, 1, 9, 4, 4, 3, 3, 3],
       [6, 4, 5, 8, 9, 1, 5, 8, 3],
       [6, 8, 1, 1, 6, 8, 8, 5, 7],
       [7, 9, 9, 5, 3, 7, 6, 2, 4],
       [8, 7, 9, 2, 4, 5, 8, 5, 8]])

In [ ]:
m1[2,5] # , (coma) : first number is for row and second number is for column,

np.int64(2)

In [ ]:
m1[2:4] # : (colen) used for splitting

array([[2, 8, 4, 6, 7, 2, 5, 9, 6],
       [1, 3, 5, 4, 3, 6, 9, 8, 7]])

# How to print coloumn

In [ ]:
m

array([[1, 3, 7, 1, 5, 5, 5, 2, 1],
       [4, 7, 7, 3, 8, 3, 7, 1, 7],
       [2, 8, 4, 6, 7, 2, 5, 9, 6],
       [1, 3, 5, 4, 3, 6, 9, 8, 7],
       [9, 3, 1, 9, 4, 4, 3, 3, 3],
       [6, 4, 5, 8, 9, 1, 5, 8, 3],
       [6, 8, 1, 1, 6, 8, 8, 5, 7],
       [7, 9, 9, 5, 3, 7, 6, 2, 4],
       [8, 7, 9, 2, 4, 5, 8, 5, 8]])

In [ ]:
m[:,0] # 

array([1, 4, 2, 1, 9, 6, 6, 7, 8])

In [ ]:
m[:,-3]

array([5, 7, 5, 9, 3, 5, 8, 6, 8])

In [ ]:
m1[2:]

array([[2, 8, 4, 6, 7, 2, 5, 9, 6],
       [1, 3, 5, 4, 3, 6, 9, 8, 7],
       [9, 3, 1, 9, 4, 4, 3, 3, 3],
       [6, 4, 5, 8, 9, 1, 5, 8, 3],
       [6, 8, 1, 1, 6, 8, 8, 5, 7],
       [7, 9, 9, 5, 3, 7, 6, 2, 4],
       [8, 7, 9, 2, 4, 5, 8, 5, 8]])

In [ ]:
m1

array([[1, 3, 7, 1, 5, 5, 5, 2, 1],
       [4, 7, 7, 3, 8, 3, 7, 1, 7],
       [2, 8, 4, 6, 7, 2, 5, 9, 6],
       [1, 3, 5, 4, 3, 6, 9, 8, 7],
       [9, 3, 1, 9, 4, 4, 3, 3, 3],
       [6, 4, 5, 8, 9, 1, 5, 8, 3],
       [6, 8, 1, 1, 6, 8, 8, 5, 7],
       [7, 9, 9, 5, 3, 7, 6, 2, 4],
       [8, 7, 9, 2, 4, 5, 8, 5, 8]])

In [ ]:
m1[:4]# will dispaly upto 3, cos it is always n-1 .

array([[1, 3, 7, 1, 5, 5, 5, 2, 1],
       [4, 7, 7, 3, 8, 3, 7, 1, 7],
       [2, 8, 4, 6, 7, 2, 5, 9, 6],
       [1, 3, 5, 4, 3, 6, 9, 8, 7]])

In [ ]:
m1[1:4,1:3]

array([[7, 7],
       [8, 4],
       [3, 5]])

In [ ]:
m1[3:8,3:8]

array([[4, 3, 6, 9, 8],
       [9, 4, 4, 3, 3],
       [8, 9, 1, 5, 8],
       [1, 6, 8, 8, 5],
       [5, 3, 7, 6, 2]])

# Masking or filter in matrix

In [ ]:
m1


array([[1, 3, 7, 1, 5, 5, 5, 2, 1],
       [4, 7, 7, 3, 8, 3, 7, 1, 7],
       [2, 8, 4, 6, 7, 2, 5, 9, 6],
       [1, 3, 5, 4, 3, 6, 9, 8, 7],
       [9, 3, 1, 9, 4, 4, 3, 3, 3],
       [6, 4, 5, 8, 9, 1, 5, 8, 3],
       [6, 8, 1, 1, 6, 8, 8, 5, 7],
       [7, 9, 9, 5, 3, 7, 6, 2, 4],
       [8, 7, 9, 2, 4, 5, 8, 5, 8]])

In [ ]:
m1.shape

(9, 9)

In [ ]:
id(m1)

4803710288

In [ ]:
type(m1)

numpy.ndarray

In [ ]:
m1<10

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True]])

In [ ]:
m1<5

array([[ True,  True, False,  True, False, False, False,  True,  True],
       [ True, False, False,  True, False,  True, False,  True, False],
       [ True, False,  True, False, False,  True, False, False, False],
       [ True,  True, False,  True,  True, False, False, False, False],
       [False,  True,  True, False,  True,  True,  True,  True,  True],
       [False,  True, False, False, False,  True, False, False,  True],
       [False, False,  True,  True, False, False, False, False, False],
       [False, False, False, False,  True, False, False,  True,  True],
       [False, False, False,  True,  True, False, False, False, False]])

In [ ]:
m1[m1<5]

array([1, 3, 1, 2, 1, 4, 3, 3, 1, 2, 4, 2, 1, 3, 4, 3, 3, 1, 4, 4, 3, 3,
       3, 4, 1, 3, 1, 1, 3, 2, 4, 2, 4])

In [ ]:
m1[m1<=5]

array([1, 3, 1, 5, 5, 5, 2, 1, 4, 3, 3, 1, 2, 4, 2, 5, 1, 3, 5, 4, 3, 3,
       1, 4, 4, 3, 3, 3, 4, 5, 1, 5, 3, 1, 1, 5, 5, 3, 2, 4, 2, 4, 5, 5])

In [ ]:
m1[m1!=5]

array([1, 3, 7, 1, 2, 1, 4, 7, 7, 3, 8, 3, 7, 1, 7, 2, 8, 4, 6, 7, 2, 9,
       6, 1, 3, 4, 3, 6, 9, 8, 7, 9, 3, 1, 9, 4, 4, 3, 3, 3, 6, 4, 8, 9,
       1, 8, 3, 6, 8, 1, 1, 6, 8, 8, 7, 7, 9, 9, 3, 7, 6, 2, 4, 8, 7, 9,
       2, 4, 8, 8])

In [ ]:
m1[m1==5]

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [178]:
m1

array([[4, 3, 2, 6, 3, 8, 6, 8, 1],
       [3, 8, 5, 3, 3, 3, 8, 1, 9],
       [5, 4, 7, 3, 6, 2, 8, 9, 3],
       [9, 8, 4, 4, 7, 8, 7, 8, 2],
       [2, 8, 8, 5, 7, 7, 8, 1, 9],
       [8, 2, 7, 3, 8, 7, 9, 7, 4],
       [7, 2, 7, 4, 5, 3, 2, 9, 5],
       [1, 8, 8, 6, 6, 3, 2, 1, 9],
       [1, 3, 5, 7, 3, 7, 3, 4, 4]])

In [ ]:
m1[m1>5]

array([7, 7, 7, 8, 7, 7, 8, 6, 7, 9, 6, 6, 9, 8, 7, 9, 9, 6, 8, 9, 8, 6,
       8, 6, 8, 8, 7, 7, 9, 9, 7, 6, 8, 7, 9, 8, 8])

In [179]:
m1

array([[4, 3, 2, 6, 3, 8, 6, 8, 1],
       [3, 8, 5, 3, 3, 3, 8, 1, 9],
       [5, 4, 7, 3, 6, 2, 8, 9, 3],
       [9, 8, 4, 4, 7, 8, 7, 8, 2],
       [2, 8, 8, 5, 7, 7, 8, 1, 9],
       [8, 2, 7, 3, 8, 7, 9, 7, 4],
       [7, 2, 7, 4, 5, 3, 2, 9, 5],
       [1, 8, 8, 6, 6, 3, 2, 1, 9],
       [1, 3, 5, 7, 3, 7, 3, 4, 4]])