# NumPy : Advance functionalities

In [1]:
import numpy as np

In [2]:
# create an array from list
list = [1,2,3]
a = np.array(list)
print("Array a = ",a)

Array a =  [1 2 3]


In [3]:
# create an array with evenly spaced balues
b= np.arange(0,10,3) # values from 0 to 10 with step 3
print("Array b = ",b)

Array b =  [0 3 6 9]


In [4]:
# create an array filled with zeros
d = np.zeros((2,3)) # create a 2X3 array of zeros as default values, adds floats by default
print("Arrau d: \n",d)

# this is example for parameter

Arrau d: 
 [[0. 0. 0.]
 [0. 0. 0.]]


In [5]:
# create an array filled with zeros
d = np.zeros((2,3), dtype=int) # create a 2X3 array of zeros as default values, dtype as int for whole number
print("Array d: \n",d) 

# this is example for hyperparameter

Array d: 
 [[0 0 0]
 [0 0 0]]


In [6]:
e = np.ones((3,2)) # 3X2 array of ones as default values, with default float values
print("Array e = ",e)

Array e =  [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [7]:
e = np.ones((3,2), dtype=int) # 3X2 array of ones as default values, with default int values
print("Array e = ",e)

Array e =  [[1 1]
 [1 1]
 [1 1]]


In [8]:
# create an identity matrix
f = np.eye(4) # a matrix whose diagnol elements are all 1, is called identity matrix
print("Identity matrix = \n",f)

Identity matrix = 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [9]:
# create an identity matrix
f = np.eye(3,6) # a matrix whose diagnol elements are all 1, is called identity matrix
print("Identity matrix = \n",f)

Identity matrix = 
 [[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]


# Array Manipulation Functions

In [10]:
# Reshape an array
a1= np.array([1,2,3])
print("Original Array = ",a1)
print("Original Array shape = ",a1.shape)
reshaped = np.reshape(a1,(1,3))
print("Reshaped array = ",reshaped)
print("Reshaped array shape = ",reshaped.shape)

Original Array =  [1 2 3]
Original Array shape =  (3,)
Reshaped array =  [[1 2 3]]
Reshaped array shape =  (1, 3)


In [11]:
# Reshape an array
a1= np.array([1,2,3])
print("Original Array = ",a1)
print("Original Array shape = ",a1.shape)
reshaped = np.reshape(a1,(3,1))
print("Reshaped array = \n",reshaped)
print("Reshaped array shape = ",reshaped.shape)

Original Array =  [1 2 3]
Original Array shape =  (3,)
Reshaped array = 
 [[1]
 [2]
 [3]]
Reshaped array shape =  (3, 1)


In [12]:
# Flatten an array
f1 = np.array([[1,2],[3,4],[5,6],[7,8],[8,9],[9,10]])
print("f1 array = \n",f1)
flattened = np.ravel(f1)
print("Flattened array = ",flattened)

f1 array = 
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 8  9]
 [ 9 10]]
Flattened array =  [ 1  2  3  4  5  6  7  8  8  9  9 10]


In [13]:
# Transpose an array
e1 = np.array([[1,2],[3,4]])
transposed = np.transpose(e1)
print("Transposed array = \n",transposed)

Transposed array = 
 [[1 3]
 [2 4]]


In [14]:
# stack arrays vertically
a2 = np.array([1,2])
b2 = np.array([3,4])
stacked = np.vstack([a2,b2])
print("Vertical stacking = \n",stacked)

Vertical stacking = 
 [[1 2]
 [3 4]]


In [15]:
# stack arrays Horizontally
a2 = np.array([1,2,])
b2 = np.array([3,4])
stacked = np.hstack([a2,b2])
print("Horizontal stacking = \n",stacked)

Horizontal stacking = 
 [1 2 3 4]


# Mathematical Functions

In [16]:
# Add two arrays
g  = np.array([1,2,3,4])
added = np.add(g,2) # add 2 to each element
print("Added 2 to each element \n",added)


Added 2 to each element 
 [3 4 5 6]


In [17]:
# square of each element
squared = np.power(g,2) # square each element in g
print("Suqare all the value \n",squared)

Suqare all the value 
 [ 1  4  9 16]


In [18]:
# square root of each element
sq = np.array([4,9,16,25,36])
sqrt_value = np.sqrt(sq)
print("The square root of array sq = \n", sqrt_value)

The square root of array sq = 
 [2. 3. 4. 5. 6.]


In [19]:
a3 = np.array([1,2,3,4])
g  = np.array([1,2,3,4])
print(a)
print(a3)
print(g)


[1 2 3]
[1 2 3 4]
[1 2 3 4]


In [20]:
# dot product
dot_product = np.dot(a,g) # Dot product of a and g , multiply and sum all elements
print("Dot product of a and g : ",dot_product)


ValueError: shapes (3,) and (4,) not aligned: 3 (dim 0) != 4 (dim 0)

In [ ]:
# dot product
dot_product = np.dot(a3,g) # Dot product of a and g , multiply and sum all elements
print("Dot product of a and g : ",dot_product)


Dot product of a and g :  30


# Statistical Functions

In [ ]:
s = np.array([1,2,3,4])
mean = np.mean(s)
print(f"The mean value of  s  = {mean}")

The mean value of  s  = 2.5


In [ ]:
# standard deviation of an array
s = np.array([1,2,3,4,5])
var = np.var(s)
print("The values = ",s)
print("Variance of s = ", var)

The values =  [1 2 3 4 5]
Variance of s =  2.0


In [ ]:
# standard devication of an array
print("The values = ",s)
std_dev = np.std(s)
print("Standard deviation of s: ",std_dev)

The values =  [1 2 3 4 5]
Standard deviation of s:  1.4142135623730951


In [ ]:
# minimum element of an array
minimum = np.min(s)
print("The minimum value = ", minimum)

The minimum value =  1


In [ ]:
# Maximum element of an array
maximum = np.max(s)
print("The maximumm value = ", maximum)

The maximumm value =  4


# Linear Algebra

In [ ]:
# create a matrix
matrix = np.array([[1,2],[3,4]])
print("The matrix : \n", matrix)

The matrix : 
 [[1 2]
 [3 4]]


# Random Sampling Functions


In [ ]:
# generate a random value between 0 and 1
random_val= np.random.rand(3) # array of 3 randome values between 0 and 1
print("Random values : ",random_val)

Random values :  [0.07401935 0.66451206 0.04552319]


In [ ]:
# set seed for reproducibility
# np.random.seed(0) # seed to restrict generation of multiple

random_val = np.random.rand(3)
print("Randome number : ",random_val)

Randome number :  [0.5488135  0.71518937 0.60276338]


In [ ]:
# Generate random number
np.random.seed(0)
random_val = np.random.randint(1,9,size=6)
print("The randome : OTP : ",random_val)

The randome : OTP :  [5 8 6 1 4 4]


# Boolean and Logical Functions

In [ ]:
# check if all elements are True
#all

logical_test= np.array([True, False,True])
all_true = np.all(logical_test)
print("Are all elements True ? :",all_true)

Are all elements True ? : False


In [ ]:
# check if all elements are True
#all

logical_test= np.array([True, True,True])
all_true = np.all(logical_test)
print("Are all elements True ? :",all_true)

Are all elements True ? : True


In [ ]:
# check if all elements are True
#any

logical_test= np.array([False, False,True])
any_true = np.any(logical_test)
print("Are any elements True ? :",any_true)

Are any elements True ? : True


In [ ]:
# check if all elements are True
#any

logical_test= np.array([False, False, False])
any_true = np.any(logical_test)
print("Are any elements True ? :",any_true)

Are any elements True ? : False


# Set Operation

In [ ]:
# Intersection of two arrays
set_a = np.array([1,2,3,4])
set_b= np.array([3,4,5,6])
intersection = np.intersect1d(set_a, set_b)
print("Ther intersect1d of set_a and set_b = ",intersection)

Ther intersect1d of set_a and set_b =  [3 4]


In [ ]:
set_a = np.array([1,2,3,4])
set_b= np.array([3,4,5,6])
union_val = np.union1d(set_a, set_b)
print("Ther union1d of set_a and set_b = ",union_val)

Ther union1d of set_a and set_b =  [1 2 3 4 5 6]


# Array Attribute Functions

In [ ]:
# Array Attributes
a = np.array([1,2,3])

print("Shape of array a = ", a.shape)
print("Size of array a = ", a.size)
print("Number of dimensions of array = ",a.ndim)
print("Data type of array a = ",a.dtype)

Shape of array a =  (3,)
Size of array a =  3
Number of dimensions of array =  1
Data type of array a =  int64


# Other Functions

In [ ]:
a = np.array([1,2,3])

copy_array = np.copy(a) # create a copy of array a
print("Copied Array = ",copy_array)


array_size_in_bytes = a.nbytes
print("The size of array a in bytes = ", array_size_in_bytes)

#Check if two arrays share memory
shared = np.shares_memory(a, copy_array)
print("Do a and copy_array share memory", shared)
print("-- id of a = ",id(a))
print("-- id of copy_array = ",id(copy_array))

Copied Array =  [1 2 3]
The size of array a in bytes =  24
Do a and copy_array share memory False
-- id of a =  4760164592
-- id of copy_array =  4760162384
