# NumPy : Advance functionalities

In [54]:
import numpy as np

In [55]:
# create an array from list
list = [1,2,3]
a = np.array(list)
print("Array a = ",a)

Array a =  [1 2 3]


In [56]:
# create an array with evenly spaced balues
b= np.arange(0,10,3) # values from 0 to 10 with step 3
print("Array b = ",b)

Array b =  [0 3 6 9]


In [57]:
# create an array filled with zeros
d = np.zeros((2,3)) # create a 2X3 array of zeros as default values, adds floats by default
print("Arrau d: \n",d)

# this is example for parameter

Arrau d: 
 [[0. 0. 0.]
 [0. 0. 0.]]


In [58]:
# create an array filled with zeros
d = np.zeros((2,3), dtype=int) # create a 2X3 array of zeros as default values, dtype as int for whole number
print("Array d: \n",d) 

# this is example for hyperparameter

Array d: 
 [[0 0 0]
 [0 0 0]]


In [59]:
e = np.ones((3,2)) # 3X2 array of ones as default values, with default float values
print("Array e = ",e)

Array e =  [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [60]:
e = np.ones((3,2), dtype=int) # 3X2 array of ones as default values, with default int values
print("Array e = ",e)

Array e =  [[1 1]
 [1 1]
 [1 1]]


In [61]:
# create an identity matrix
f = np.eye(4) # a matrix whose diagnol elements are all 1, is called identity matrix
print("Identity matrix = ",f)

Identity matrix =  [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# Array Manipulation Functions

In [62]:
# Reshape an array
a1= np.array([1,2,3])
print("Original Array = ",a1)
print("Original Array shape = ",a1.shape)
reshaped = np.reshape(a1,(1,3))
print("Reshaped array = ",reshaped)
print("Reshaped array shape = ",reshaped.shape)

Original Array =  [1 2 3]
Original Array shape =  (3,)
Reshaped array =  [[1 2 3]]
Reshaped array shape =  (1, 3)


In [63]:
# Reshape an array
a1= np.array([1,2,3])
print("Original Array = ",a1)
print("Original Array shape = ",a1.shape)
reshaped = np.reshape(a1,(3,1))
print("Reshaped array = \n",reshaped)
print("Reshaped array shape = ",reshaped.shape)

Original Array =  [1 2 3]
Original Array shape =  (3,)
Reshaped array = 
 [[1]
 [2]
 [3]]
Reshaped array shape =  (3, 1)


In [67]:
# Flatten an array
f1 = np.array([[1,2],[3,4],[5,6],[7,8],[8,9],[9,10]])
print("f1 array = \n",f1)
flattened = np.ravel(f1)
print("Flattened array = ",flattened)

f1 array = 
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 8  9]
 [ 9 10]]
Flattened array =  [ 1  2  3  4  5  6  7  8  8  9  9 10]


In [65]:
# Transpose an array
e1 = np.array([[1,2],[3,4]])
transposed = np.transpose(e1)
print("Transposed array = \n",transposed)

Transposed array = 
 [[1 3]
 [2 4]]
