# numpy: part 2


In [1]:
import numpy as np

In [ ]:
m = np.random.randint(1,10,(4,6)) # (4,6)4 rows, 6 columns, and values ranging from 1 to 10.
print(m)


[[1 8 5 1 2 4]
 [7 7 8 6 4 6]
 [1 1 9 3 6 8]
 [1 3 4 7 6 4]]


array([[1, 8, 5, 1, 2, 4],
       [7, 7, 8, 6, 4, 6],
       [1, 1, 9, 3, 6, 8],
       [1, 3, 4, 7, 6, 4]])

In [23]:

print(len(m))

9


In [9]:
m

array([[1, 8, 5, 1, 2, 4],
       [7, 7, 8, 6, 4, 6],
       [1, 1, 9, 3, 6, 8],
       [1, 3, 4, 7, 6, 4]])

In [10]:
m[:]

array([[1, 8, 5, 1, 2, 4],
       [7, 7, 8, 6, 4, 6],
       [1, 1, 9, 3, 6, 8],
       [1, 3, 4, 7, 6, 4]])

In [12]:
m[2]

array([1, 1, 9, 3, 6, 8])

In [13]:
m1 = m = np.random.randint(1,10,(9,9))
m1

array([[1, 3, 7, 1, 5, 5, 5, 2, 1],
       [4, 7, 7, 3, 8, 3, 7, 1, 7],
       [2, 8, 4, 6, 7, 2, 5, 9, 6],
       [1, 3, 5, 4, 3, 6, 9, 8, 7],
       [9, 3, 1, 9, 4, 4, 3, 3, 3],
       [6, 4, 5, 8, 9, 1, 5, 8, 3],
       [6, 8, 1, 1, 6, 8, 8, 5, 7],
       [7, 9, 9, 5, 3, 7, 6, 2, 4],
       [8, 7, 9, 2, 4, 5, 8, 5, 8]])

In [ ]:
m1[0:9:3] # from 0 to 9 but step slice it by 3 

array([[1, 3, 7, 1, 5, 5, 5, 2, 1],
       [1, 3, 5, 4, 3, 6, 9, 8, 7],
       [6, 8, 1, 1, 6, 8, 8, 5, 7]])

In [15]:
m1[::2]

array([[1, 3, 7, 1, 5, 5, 5, 2, 1],
       [2, 8, 4, 6, 7, 2, 5, 9, 6],
       [9, 3, 1, 9, 4, 4, 3, 3, 3],
       [6, 8, 1, 1, 6, 8, 8, 5, 7],
       [8, 7, 9, 2, 4, 5, 8, 5, 8]])

In [16]:
m1[::5]

array([[1, 3, 7, 1, 5, 5, 5, 2, 1],
       [6, 4, 5, 8, 9, 1, 5, 8, 3]])

In [17]:
m1[::-1]

array([[8, 7, 9, 2, 4, 5, 8, 5, 8],
       [7, 9, 9, 5, 3, 7, 6, 2, 4],
       [6, 8, 1, 1, 6, 8, 8, 5, 7],
       [6, 4, 5, 8, 9, 1, 5, 8, 3],
       [9, 3, 1, 9, 4, 4, 3, 3, 3],
       [1, 3, 5, 4, 3, 6, 9, 8, 7],
       [2, 8, 4, 6, 7, 2, 5, 9, 6],
       [4, 7, 7, 3, 8, 3, 7, 1, 7],
       [1, 3, 7, 1, 5, 5, 5, 2, 1]])

In [ ]:
m1[-1]# reversed only th efirst row

array([8, 7, 9, 2, 4, 5, 8, 5, 8])

In [20]:
m

array([[1, 3, 7, 1, 5, 5, 5, 2, 1],
       [4, 7, 7, 3, 8, 3, 7, 1, 7],
       [2, 8, 4, 6, 7, 2, 5, 9, 6],
       [1, 3, 5, 4, 3, 6, 9, 8, 7],
       [9, 3, 1, 9, 4, 4, 3, 3, 3],
       [6, 4, 5, 8, 9, 1, 5, 8, 3],
       [6, 8, 1, 1, 6, 8, 8, 5, 7],
       [7, 9, 9, 5, 3, 7, 6, 2, 4],
       [8, 7, 9, 2, 4, 5, 8, 5, 8]])

In [19]:
m[::-4]

array([[8, 7, 9, 2, 4, 5, 8, 5, 8],
       [9, 3, 1, 9, 4, 4, 3, 3, 3],
       [1, 3, 7, 1, 5, 5, 5, 2, 1]])

In [25]:
my_list= [0,1,2,3,4,5]
arr = np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [28]:
arr.shape

(6,)

In [32]:
m1.shape # 


(9, 9)

In [34]:
m1.reshape(6,6) # reshaping should match with the original number of elements already in the beginning

ValueError: cannot reshape array of size 81 into shape (6,6)

In [35]:
m2 = np.random.randint(1,10,(2,3))

In [36]:
m2.shape

(2, 3)

In [40]:
m2

array([[2, 9, 2],
       [9, 8, 6]])

In [42]:
m2.reshape(6,1) # since the number are matching it will reshape the matrix.

array([[2],
       [9],
       [2],
       [9],
       [8],
       [6]])

In [44]:
m1

array([[1, 3, 7, 1, 5, 5, 5, 2, 1],
       [4, 7, 7, 3, 8, 3, 7, 1, 7],
       [2, 8, 4, 6, 7, 2, 5, 9, 6],
       [1, 3, 5, 4, 3, 6, 9, 8, 7],
       [9, 3, 1, 9, 4, 4, 3, 3, 3],
       [6, 4, 5, 8, 9, 1, 5, 8, 3],
       [6, 8, 1, 1, 6, 8, 8, 5, 7],
       [7, 9, 9, 5, 3, 7, 6, 2, 4],
       [8, 7, 9, 2, 4, 5, 8, 5, 8]])

In [ ]:
m1[2,5] # , (coma) : first number is for row and second number is for column,

np.int64(2)

In [ ]:
m1[2:4] # : (colen) used for splitting

array([[2, 8, 4, 6, 7, 2, 5, 9, 6],
       [1, 3, 5, 4, 3, 6, 9, 8, 7]])

# How to print coloumn

In [50]:
m

array([[1, 3, 7, 1, 5, 5, 5, 2, 1],
       [4, 7, 7, 3, 8, 3, 7, 1, 7],
       [2, 8, 4, 6, 7, 2, 5, 9, 6],
       [1, 3, 5, 4, 3, 6, 9, 8, 7],
       [9, 3, 1, 9, 4, 4, 3, 3, 3],
       [6, 4, 5, 8, 9, 1, 5, 8, 3],
       [6, 8, 1, 1, 6, 8, 8, 5, 7],
       [7, 9, 9, 5, 3, 7, 6, 2, 4],
       [8, 7, 9, 2, 4, 5, 8, 5, 8]])

In [ ]:
m[:,0] # 

array([1, 4, 2, 1, 9, 6, 6, 7, 8])

In [51]:
m[:,-3]

array([5, 7, 5, 9, 3, 5, 8, 6, 8])

In [52]:
m1[2:]

array([[2, 8, 4, 6, 7, 2, 5, 9, 6],
       [1, 3, 5, 4, 3, 6, 9, 8, 7],
       [9, 3, 1, 9, 4, 4, 3, 3, 3],
       [6, 4, 5, 8, 9, 1, 5, 8, 3],
       [6, 8, 1, 1, 6, 8, 8, 5, 7],
       [7, 9, 9, 5, 3, 7, 6, 2, 4],
       [8, 7, 9, 2, 4, 5, 8, 5, 8]])

In [53]:
m1

array([[1, 3, 7, 1, 5, 5, 5, 2, 1],
       [4, 7, 7, 3, 8, 3, 7, 1, 7],
       [2, 8, 4, 6, 7, 2, 5, 9, 6],
       [1, 3, 5, 4, 3, 6, 9, 8, 7],
       [9, 3, 1, 9, 4, 4, 3, 3, 3],
       [6, 4, 5, 8, 9, 1, 5, 8, 3],
       [6, 8, 1, 1, 6, 8, 8, 5, 7],
       [7, 9, 9, 5, 3, 7, 6, 2, 4],
       [8, 7, 9, 2, 4, 5, 8, 5, 8]])

In [55]:
m1[:4]# will dispaly upto 3, cos it is always n-1 .

array([[1, 3, 7, 1, 5, 5, 5, 2, 1],
       [4, 7, 7, 3, 8, 3, 7, 1, 7],
       [2, 8, 4, 6, 7, 2, 5, 9, 6],
       [1, 3, 5, 4, 3, 6, 9, 8, 7]])

In [56]:
m1[1:4,1:3]

array([[7, 7],
       [8, 4],
       [3, 5]])

In [58]:
m1[3:8,3:8]

array([[4, 3, 6, 9, 8],
       [9, 4, 4, 3, 3],
       [8, 9, 1, 5, 8],
       [1, 6, 8, 8, 5],
       [5, 3, 7, 6, 2]])

# Masking or filter in matrix

In [59]:
m1


array([[1, 3, 7, 1, 5, 5, 5, 2, 1],
       [4, 7, 7, 3, 8, 3, 7, 1, 7],
       [2, 8, 4, 6, 7, 2, 5, 9, 6],
       [1, 3, 5, 4, 3, 6, 9, 8, 7],
       [9, 3, 1, 9, 4, 4, 3, 3, 3],
       [6, 4, 5, 8, 9, 1, 5, 8, 3],
       [6, 8, 1, 1, 6, 8, 8, 5, 7],
       [7, 9, 9, 5, 3, 7, 6, 2, 4],
       [8, 7, 9, 2, 4, 5, 8, 5, 8]])

In [60]:
m1.shape

(9, 9)

In [61]:
id(m1)

4803710288

In [62]:
type(m1)

numpy.ndarray

In [63]:
m1<10

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True]])

In [64]:
m1<5

array([[ True,  True, False,  True, False, False, False,  True,  True],
       [ True, False, False,  True, False,  True, False,  True, False],
       [ True, False,  True, False, False,  True, False, False, False],
       [ True,  True, False,  True,  True, False, False, False, False],
       [False,  True,  True, False,  True,  True,  True,  True,  True],
       [False,  True, False, False, False,  True, False, False,  True],
       [False, False,  True,  True, False, False, False, False, False],
       [False, False, False, False,  True, False, False,  True,  True],
       [False, False, False,  True,  True, False, False, False, False]])

In [65]:
m1[m1<5]

array([1, 3, 1, 2, 1, 4, 3, 3, 1, 2, 4, 2, 1, 3, 4, 3, 3, 1, 4, 4, 3, 3,
       3, 4, 1, 3, 1, 1, 3, 2, 4, 2, 4])

In [67]:
m1[m1<=5]

array([1, 3, 1, 5, 5, 5, 2, 1, 4, 3, 3, 1, 2, 4, 2, 5, 1, 3, 5, 4, 3, 3,
       1, 4, 4, 3, 3, 3, 4, 5, 1, 5, 3, 1, 1, 5, 5, 3, 2, 4, 2, 4, 5, 5])

In [68]:
m1[m1!=5]

array([1, 3, 7, 1, 2, 1, 4, 7, 7, 3, 8, 3, 7, 1, 7, 2, 8, 4, 6, 7, 2, 9,
       6, 1, 3, 4, 3, 6, 9, 8, 7, 9, 3, 1, 9, 4, 4, 3, 3, 3, 6, 4, 8, 9,
       1, 8, 3, 6, 8, 1, 1, 6, 8, 8, 7, 7, 9, 9, 3, 7, 6, 2, 4, 8, 7, 9,
       2, 4, 8, 8])

In [69]:
m1[m1==5]

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [70]:
m1[m1>5]

array([7, 7, 7, 8, 7, 7, 8, 6, 7, 9, 6, 6, 9, 8, 7, 9, 9, 6, 8, 9, 8, 6,
       8, 6, 8, 8, 7, 7, 9, 9, 7, 6, 8, 7, 9, 8, 8])