In [72]:
import numpy as np

# Create a 3x3 matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# 1. Get the total for EACH individual column
column_totals = np.sum(matrix, axis=0)

# 2. Get the GRAND total of everything combined
grand_total = np.sum(matrix)

print("Individual Column Totals:", column_totals)
print("Grand Total of Matrix:   ", grand_total)

Individual Column Totals: [12 15 18]
Grand Total of Matrix:    45


In [73]:
# random 3X3 matrix with values ranging from 1 to 10
matrix3x3 = np.random.randint(1,10,(3,3))
matrix3x3

array([[8, 2, 6],
       [1, 8, 9],
       [6, 8, 5]])

In this practice problem, we want you to extract all even values from a 2-dimensional array. The result should be a 1-dimensional array that contains all even values of the provided 2-dimensional array.

Recall that the even numbers are 0, 2, 4, 6, and so on.

For example, if the 2-dimensional array was:

[[1 2 4]

 [3 4 6]]

In [125]:
# Answer
all_values=np.array([[1,2,4],[3,4,6]])
even_values = all_values[all_values % 2 ==0]
mask = [all_values % 2 ==0]
print(f"Mask = {mask}")
# even_values = all_values[mask]

print(f"The original matrix = \n{all_values}\n")
print(f"The resultant even numbers = {even_values}")



Mask = [array([[False,  True,  True],
       [False,  True,  True]])]
The original matrix = 
[[1 2 4]
 [3 4 6]]

The resultant even numbers = [2 4 4 6]


In [75]:
import numpy as np

# Initial setup
arr = np.array([[1, 2, 4], 
                [3, 4, 6]])

print("--- Step 0: Original Array ---")
print(arr)

# STEP 1: Create the Boolean Mask
# This evaluates the condition for every element
mask = (arr % 2 != 0)
print("\n--- Step 1: The Mask (Identifying Odds) ---")
print(mask)

# STEP 2: Use the mask to select elements
# We can see what the mask "sees" before we change it
odds_detected = arr[mask]
print("\n--- Step 2: Elements identified by Mask ---")
print(odds_detected)

# STEP 3: Assignment (In-place modification)
# This replaces only the 'True' positions with 0
arr[mask] = 0
print("\n--- Step 3: Result after Assignment ---")
print(arr)

--- Step 0: Original Array ---
[[1 2 4]
 [3 4 6]]

--- Step 1: The Mask (Identifying Odds) ---
[[ True False False]
 [ True False False]]

--- Step 2: Elements identified by Mask ---
[1 3]

--- Step 3: Result after Assignment ---
[[0 2 4]
 [0 4 6]]


In [76]:
arr = np.arange(9)
print("arr = ",arr)
print( arr.reshape(3,3))

arr.flatten()


arr =  [0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [77]:
np.zeros(3)


array([0., 0., 0.])

In [78]:
np.zeros(9)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [79]:
z = np.reshape(9,1)
z

array([9])

In [80]:
type(z)

numpy.ndarray

In [81]:
z = np.empty(6)
z

array([0.e+000, 1.e-323, 2.e-323, 0.e+000, 2.e-323, 3.e-323])

In [82]:
z= np.linspace(2,10,5)
z

array([ 2.,  4.,  6.,  8., 10.])

In [83]:
z = np.array([10,20])
z

array([10, 20])

In [84]:
a_list = [1,2,3,4,5,6,7,]
z = np.array([a_list])
z

array([[1, 2, 3, 4, 5, 6, 7]])

In [85]:
b_list=[[9,8,7,6,5,4,3],[1,2,3,4,5,6,7]]
z = np.array([b_list])
z

array([[[9, 8, 7, 6, 5, 4, 3],
        [1, 2, 3, 4, 5, 6, 7]]])

In [86]:
z.shape
# ?z.shape

(1, 2, 7)

In [87]:
np.random.seed(0)
z1=np.random.randint(10,size =6)
z1

array([5, 0, 3, 3, 7, 9])

In [88]:
z1[0]

np.int64(5)

In [89]:
z1[0:2]

array([5, 0])

In [90]:
z1[-1]

np.int64(9)

In [91]:
a_array =np.array([1,2,3,4,5])
b_array =np.array([6,7,8,9,10])
c_array= np.array([11,12,13,14,15])

In [92]:
a_array+ b_array

array([ 7,  9, 11, 13, 15])

In [93]:
a_array+30

array([31, 32, 33, 34, 35])

In [94]:
a_array * b_array

array([ 6, 14, 24, 36, 50])

In [95]:
a_array @ b_array

np.int64(130)

In [96]:
a_array = [3,6,8,10,4,7,2,9,1,5,]
x = np.sort(a_array,stable=True)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [97]:
arr = np.array([[4, 1, 3],
                [2, 6, 5],
                [9, 2, 7]])

np.sort(arr, axis= 1)

array([[1, 3, 4],
       [2, 5, 6],
       [2, 7, 9]])

In [98]:
np.sort(arr, axis=0)

array([[2, 1, 3],
       [4, 2, 5],
       [9, 6, 7]])

In [99]:
np.sort(arr, axis=None)

array([1, 2, 2, 3, 4, 5, 6, 7, 9])

In [100]:
dtype = [('name', 'S20'), ('age', int), ("department", 'S20'), ('state','S10')]
values = [('Alice', 25, 'Computers', 'KA'), ('Bob', 19,'Finance','PA'), ('Charlie', 25,'Accounts','NY')]

people = np.array(values, dtype=dtype)

sorted_people = np.sort(people, order=['state','name'])
sorted_people

array([(b'Alice', 25, b'Computers', b'KA'),
       (b'Charlie', 25, b'Accounts', b'NY'),
       (b'Bob', 19, b'Finance', b'PA')],
      dtype=[('name', 'S20'), ('age', '<i8'), ('department', 'S20'), ('state', 'S10')])

In [101]:
import numpy as np
arr = [[1,2,3,4],[1,2,2,2]]

arr

[[1, 2, 3, 4], [1, 2, 2, 2]]

# Numpy : Create

In [102]:
data = np.random.rand(2,3,4)
zeroes = np.zeros((2,2,2))
full = np.full((2,2,2),7)
onese = np.ones((2,2,2))

In [103]:
print(data)
print(zeroes)
print(full)
print(onese)
type(arr)

[[[0.6235637  0.38438171 0.29753461 0.05671298]
  [0.27265629 0.47766512 0.81216873 0.47997717]
  [0.3927848  0.83607876 0.33739616 0.64817187]]

 [[0.36824154 0.95715516 0.14035078 0.87008726]
  [0.47360805 0.80091075 0.52047748 0.67887953]
  [0.72063265 0.58201979 0.53737323 0.75861562]]]
[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]
[[[7 7]
  [7 7]]

 [[7 7]
  [7 7]]]
[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


list

# Numpy :  Read

In [104]:
shape = data.shape
size = data.size
types = data.dtype

In [105]:
print(shape)
print(size)
print(types)

(2, 3, 4)
24
float64


In [106]:
# slicing
arr = data[0]
arr


array([[0.6235637 , 0.38438171, 0.29753461, 0.05671298],
       [0.27265629, 0.47766512, 0.81216873, 0.47997717],
       [0.3927848 , 0.83607876, 0.33739616, 0.64817187]])

In [107]:
slicer = data[0][0:2]
slicer

array([[0.6235637 , 0.38438171, 0.29753461, 0.05671298],
       [0.27265629, 0.47766512, 0.81216873, 0.47997717]])

In [108]:
reverse = data[-1]
reverse

array([[0.36824154, 0.95715516, 0.14035078, 0.87008726],
       [0.47360805, 0.80091075, 0.52047748, 0.67887953],
       [0.72063265, 0.58201979, 0.53737323, 0.75861562]])

In [109]:
singleval = data[0][0][0]
singleval

np.float64(0.6235636967859723)

# Numpy :  Update

In [110]:
list1 = np.random.rand(10)
list2 = np.random.rand(10)
print(list1)
print(list2)

[0.10590761 0.47360042 0.18633234 0.73691818 0.21655035 0.13521817
 0.32414101 0.14967487 0.22232139 0.38648898]
[0.90259848 0.44994999 0.61306346 0.90234858 0.09928035 0.96980907
 0.65314004 0.17090959 0.35815217 0.75068614]


In [111]:
# Basic math
add = np.add(list1,list2)
sub = np.subtract(list1,list2)
div = np.divide(list1,list2)
mult = np.multiply(list1,list2)
dot = np.dot(list1,list2)

In [112]:
print(add)
print(sub)
print(div)
print(mult)
print(dot)


[1.00850608 0.92355041 0.7993958  1.63926676 0.3158307  1.10502724
 0.97728104 0.32058445 0.58047356 1.13717512]
[-0.79669087  0.02365043 -0.42673111 -0.16543041  0.11727    -0.83459089
 -0.32899903 -0.02123472 -0.13583078 -0.36419716]
[0.11733635 1.05256235 0.30393647 0.81666685 2.18120055 0.13942762
 0.49628103 0.87575467 0.62074562 0.51484763]
[0.09559204 0.2130965  0.11423355 0.66495707 0.0214992  0.13113581
 0.21170947 0.02558087 0.07962489 0.29013192]
1.847561325935149


In [113]:
# statistical Functions
sqrt = np.sqrt(25)
ab = np.abs(-2)
pow = np.power(2,3)
log = np.log(25)
exp = np.exp([2,5])
mins = np.min(list1)
maxs = np.max(list1)


In [114]:
print(sqrt)
print(ab)
print(pow)
print(log)
print(exp)
print(mins)
print(maxs)
print()


5.0
2
8
3.2188758248682006
[  7.3890561 148.4131591]
0.10590760718779213
0.7369181771289581



In [115]:
data[0][0][0]= 700
data.sort()
data

array([[[5.67129773e-02, 2.97534607e-01, 3.84381707e-01, 7.00000000e+02],
        [2.72656295e-01, 4.77665117e-01, 4.79977172e-01, 8.12168729e-01],
        [3.37396160e-01, 3.92784796e-01, 6.48171872e-01, 8.36078764e-01]],

       [[1.40350780e-01, 3.68241540e-01, 8.70087258e-01, 9.57155159e-01],
        [4.73608045e-01, 5.20477480e-01, 6.78879530e-01, 8.00910752e-01],
        [5.37373229e-01, 5.82019792e-01, 7.20632655e-01, 7.58615624e-01]]])

In [116]:
print(data.shape)

data = data.reshape((2,2,-1))

print(data.shape)
print(data)

(2, 3, 4)
(2, 2, 6)
[[[5.67129773e-02 2.97534607e-01 3.84381707e-01 7.00000000e+02
   2.72656295e-01 4.77665117e-01]
  [4.79977172e-01 8.12168729e-01 3.37396160e-01 3.92784796e-01
   6.48171872e-01 8.36078764e-01]]

 [[1.40350780e-01 3.68241540e-01 8.70087258e-01 9.57155159e-01
   4.73608045e-01 5.20477480e-01]
  [6.78879530e-01 8.00910752e-01 5.37373229e-01 5.82019792e-01
   7.20632655e-01 7.58615624e-01]]]


In [117]:
# append to the end of zeros array
zeroes = np.zeros((8))
print(zeroes)
zeroes = np.append(zeroes, [3,4])
print(zeroes)

[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 3. 4.]


In [118]:
zeroes = np.insert(zeroes, 2,1)
print(zeroes)

[0. 0. 1. 0. 0. 0. 0. 0. 0. 3. 4.]


# Numpy : Delete

In [119]:
data

array([[[5.67129773e-02, 2.97534607e-01, 3.84381707e-01, 7.00000000e+02,
         2.72656295e-01, 4.77665117e-01],
        [4.79977172e-01, 8.12168729e-01, 3.37396160e-01, 3.92784796e-01,
         6.48171872e-01, 8.36078764e-01]],

       [[1.40350780e-01, 3.68241540e-01, 8.70087258e-01, 9.57155159e-01,
         4.73608045e-01, 5.20477480e-01],
        [6.78879530e-01, 8.00910752e-01, 5.37373229e-01, 5.82019792e-01,
         7.20632655e-01, 7.58615624e-01]]])

In [120]:
np.delete(data,0,axis=1)


array([[[0.47997717, 0.81216873, 0.33739616, 0.3927848 , 0.64817187,
         0.83607876]],

       [[0.67887953, 0.80091075, 0.53737323, 0.58201979, 0.72063265,
         0.75861562]]])

In [121]:
asset_folder_location ='/Users/chandra/Desktop/FSDS_GenAI_Training/FSDS_Classes/Python_Workspace/assets/'

file_name =asset_folder_location+"new_numpy_array_save.npy"
np.save(file_name,data)

In [122]:
file_data=np.load(file_name)
print(file_data)

print(file_data == data) # to check if the file data is equal to loaded data.



[[[5.67129773e-02 2.97534607e-01 3.84381707e-01 7.00000000e+02
   2.72656295e-01 4.77665117e-01]
  [4.79977172e-01 8.12168729e-01 3.37396160e-01 3.92784796e-01
   6.48171872e-01 8.36078764e-01]]

 [[1.40350780e-01 3.68241540e-01 8.70087258e-01 9.57155159e-01
   4.73608045e-01 5.20477480e-01]
  [6.78879530e-01 8.00910752e-01 5.37373229e-01 5.82019792e-01
   7.20632655e-01 7.58615624e-01]]]
[[[ True  True  True  True  True  True]
  [ True  True  True  True  True  True]]

 [[ True  True  True  True  True  True]
  [ True  True  True  True  True  True]]]


# 06052026: Test related work book

In [4]:
t =(1,2,3)
t1 = (3,4,5)
t3 = t+t1
print(t3)
print(t3.count(3))

(1, 2, 3, 3, 4, 5)
2


In [5]:
s={1,2,3,2,1,4}
s.add(5)
s.discard(2)
s.discard(10)
print(len(s),3 in s)

4 True
