In [1]:
import numpy as np

# Create a 3x3 matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# 1. Get the total for EACH individual column
column_totals = np.sum(matrix, axis=0)

# 2. Get the GRAND total of everything combined
grand_total = np.sum(matrix)

print("Individual Column Totals:", column_totals)
print("Grand Total of Matrix:   ", grand_total)

Individual Column Totals: [12 15 18]
Grand Total of Matrix:    45


In [2]:
# random 3X3 matrix with values ranging from 1 to 10
matrix3x3 = np.random.randint(1,10,(3,3))
matrix3x3

array([[5, 5, 5],
       [5, 1, 1],
       [9, 2, 2]])

In this practice problem, we want you to extract all even values from a 2-dimensional array. The result should be a 1-dimensional array that contains all even values of the provided 2-dimensional array.

Recall that the even numbers are 0, 2, 4, 6, and so on.

For example, if the 2-dimensional array was:

[[1 2 4]

 [3 4 6]]

In [3]:
# Answer
all_values=np.array([[1,2,4],[3,4,6]])
# even_values = all_values[all_values % 2 ==0]
mask = [all_values % 2 ==0]
print(f"Mask = {mask}")
even_values = all_values[mask]

print(f"The original matrix = \n{all_values}\n")
print(f"The resultant even numbers = {even_values}")



Mask = [array([[False,  True,  True],
       [False,  True,  True]])]


IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed

In [ ]:
import numpy as np

# Initial setup
arr = np.array([[1, 2, 4], 
                [3, 4, 6]])

print("--- Step 0: Original Array ---")
print(arr)

# STEP 1: Create the Boolean Mask
# This evaluates the condition for every element
mask = (arr % 2 != 0)
print("\n--- Step 1: The Mask (Identifying Odds) ---")
print(mask)

# STEP 2: Use the mask to select elements
# We can see what the mask "sees" before we change it
odds_detected = arr[mask]
print("\n--- Step 2: Elements identified by Mask ---")
print(odds_detected)

# STEP 3: Assignment (In-place modification)
# This replaces only the 'True' positions with 0
arr[mask] = 0
print("\n--- Step 3: Result after Assignment ---")
print(arr)

--- Step 0: Original Array ---
[[1 2 4]
 [3 4 6]]

--- Step 1: The Mask (Identifying Odds) ---
[[ True False False]
 [ True False False]]

--- Step 2: Elements identified by Mask ---
[1 3]

--- Step 3: Result after Assignment ---
[[0 2 4]
 [0 4 6]]


In [ ]:
arr = np.arange(9)
print("arr = ",arr)
print( arr.reshape(3,3))

arr.flatten()


arr =  [0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
np.zeros(3)


array([0., 0., 0.])

In [8]:
np.zeros(9)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
z = np.reshape(9,1)
z

array([9])

In [14]:
type(z)

numpy.ndarray

In [16]:
z = np.empty(6)
z

array([0., 0., 0., 0., 0., 0.])

In [23]:
z= np.linspace(2,10,5)
z

array([ 2.,  4.,  6.,  8., 10.])

In [20]:
z = np.array([10,20])
z

array([10, 20])

In [27]:
a_list = [1,2,3,4,5,6,7,]
z = np.array([a_list])
z

array([[1, 2, 3, 4, 5, 6, 7]])

In [29]:
b_list=[[9,8,7,6,5,4,3],[1,2,3,4,5,6,7]]
z = np.array([b_list])
z

array([[[9, 8, 7, 6, 5, 4, 3],
        [1, 2, 3, 4, 5, 6, 7]]])

In [32]:
z.shape
?z.shape

Type:        tuple
String form: (1, 2, 7)
Length:      3
Docstring:  
Built-in immutable sequence.

If no argument is given, the constructor returns an empty tuple.
If iterable is specified the tuple is initialized from iterable's items.

If the argument is a tuple, the return value is the same object.

In [34]:
np.random.seed(0)
z1=np.random.randint(10,size =6)
z1

array([5, 0, 3, 3, 7, 9])

In [35]:
z1[0]

np.int64(5)

In [36]:
z1[0:2]

array([5, 0])

In [37]:
z1[-1]

np.int64(9)

In [ ]:
a_array =np.array([1,2,3,4,5])
b_array =np.array([6,7,8,9,10])
c_array= np.array([11,12,13,14,15])

In [41]:
a_array+ b_array

array([ 7,  9, 11, 13, 15])

In [42]:
a_array+30

array([31, 32, 33, 34, 35])

In [43]:
a_array * b_array

array([ 6, 14, 24, 36, 50])

In [44]:
a_array @ b_array

np.int64(130)

In [50]:
a_array = [3,6,8,10,4,7,2,9,1,5,]
x = np.sort(a_array,stable=True)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [51]:
arr = np.array([[4, 1, 3],
                [2, 6, 5],
                [9, 2, 7]])

np.sort(arr, axis= 1)

array([[1, 3, 4],
       [2, 5, 6],
       [2, 7, 9]])

In [52]:
np.sort(arr, axis=0)

array([[2, 1, 3],
       [4, 2, 5],
       [9, 6, 7]])

In [53]:
np.sort(arr, axis=None)

array([1, 2, 2, 3, 4, 5, 6, 7, 9])

In [75]:
dtype = [('name', 'S20'), ('age', int), ("department", 'S20'), ('state','S10')]
values = [('Alice', 25, 'Computers', 'KA'), ('Bob', 19,'Finance','PA'), ('Charlie', 25,'Accounts','NY')]

people = np.array(values, dtype=dtype)

sorted_people = np.sort(people, order=['state','name'])
sorted_people

array([(b'Alice', 25, b'Computers', b'KA'),
       (b'Charlie', 25, b'Accounts', b'NY'),
       (b'Bob', 19, b'Finance', b'PA')],
      dtype=[('name', 'S20'), ('age', '<i8'), ('department', 'S20'), ('state', 'S10')])