In [1]:
import numpy as np

# Create a 3x3 matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# 1. Get the total for EACH individual column
column_totals = np.sum(matrix, axis=0)

# 2. Get the GRAND total of everything combined
grand_total = np.sum(matrix)

print("Individual Column Totals:", column_totals)
print("Grand Total of Matrix:   ", grand_total)

Individual Column Totals: [12 15 18]
Grand Total of Matrix:    45


In [2]:
# random 3X3 matrix with values ranging from 1 to 10
matrix3x3 = np.random.randint(1,10,(3,3))
matrix3x3

array([[4, 7, 2],
       [7, 6, 2],
       [1, 8, 1]])

In this practice problem, we want you to extract all even values from a 2-dimensional array. The result should be a 1-dimensional array that contains all even values of the provided 2-dimensional array.

Recall that the even numbers are 0, 2, 4, 6, and so on.

For example, if the 2-dimensional array was:

[[1 2 4]

 [3 4 6]]

In [15]:
# Answer
all_values=np.array([[1,2,4],[3,4,6]])
# even_values = all_values[all_values % 2 ==0]
mask = [all_values % 2 ==0]
print(f"Mask = {mask}")
even_values = all_values[mask]

print(f"The original matrix = \n{all_values}\n")
print(f"The resultant even numbers = {even_values}")



Mask = [array([[False,  True,  True],
       [False,  True,  True]])]


IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed

In [16]:
import numpy as np

# Initial setup
arr = np.array([[1, 2, 4], 
                [3, 4, 6]])

print("--- Step 0: Original Array ---")
print(arr)

# STEP 1: Create the Boolean Mask
# This evaluates the condition for every element
mask = (arr % 2 != 0)
print("\n--- Step 1: The Mask (Identifying Odds) ---")
print(mask)

# STEP 2: Use the mask to select elements
# We can see what the mask "sees" before we change it
odds_detected = arr[mask]
print("\n--- Step 2: Elements identified by Mask ---")
print(odds_detected)

# STEP 3: Assignment (In-place modification)
# This replaces only the 'True' positions with 0
arr[mask] = 0
print("\n--- Step 3: Result after Assignment ---")
print(arr)

--- Step 0: Original Array ---
[[1 2 4]
 [3 4 6]]

--- Step 1: The Mask (Identifying Odds) ---
[[ True False False]
 [ True False False]]

--- Step 2: Elements identified by Mask ---
[1 3]

--- Step 3: Result after Assignment ---
[[0 2 4]
 [0 4 6]]


In [25]:
arr = np.arange(9)
print("arr = ",arr)
print( arr.reshape(3,3))

arr.flatten()


arr =  [0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([0, 1, 2, 3, 4, 5, 6, 7, 8])