In [1]:
import numpy as np
import pandas as pd

print("pandas version:", pd.__version__)
print("NumPy version:", np.__version__)

pandas version: 2.3.3
NumPy version: 2.5.2


In [2]:
# legacy_aliases = {
#     'long': getattr(np, 'int64', int),
#     'ulong': getattr(np, 'uint64', int),
#     'int': getattr(np, 'int_', int),
#     'float': getattr(np, 'float_', float),
#     'bool': getattr(np, 'bool_', bool),
#     'object': getattr(np, 'object_', object)
# }

# for _attr, _type in legacy_aliases.items():
#     if not hasattr(np, _attr):
#         setattr(np, _attr, _type)

In [3]:
# if not hasattr(np, 'long'):
#     np.long = int  # Restores legacy alias before TensorFlow/Keras checks it

import tensorflow as tf
print("TensorFlow Version:", tf.__version__)

TensorFlow Version: 2.18.0


In [4]:
import os

folder_path =os.getcwd()
file_name='/Churn_Modelling.csv'

full_file_path = folder_path+file_name
print('Full File Path = ',full_file_path)

Full File Path =  /Users/chandra/Desktop/FSDS_GenAI_Training/FSDS_Classes/Python_Workspace/DeepLearning/Churn_Modelling.csv


In [5]:
dataset = pd.read_csv(f""+full_file_path)
dataset.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [6]:
dataset.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0


In [7]:
X = dataset.iloc[:,3:-1]
y = dataset.iloc[:,-1]

X

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,619,France,Female,42,2,0.00,1,1,1,101348.88
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58
2,502,France,Female,42,8,159660.80,3,1,0,113931.57
3,699,France,Female,39,1,0.00,2,0,0,93826.63
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10
...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77
9997,709,France,Female,36,7,0.00,1,0,1,42085.58
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52


In [8]:
X.columns

Index(['CreditScore', 'Geography', 'Gender', 'Age', 'Tenure', 'Balance',
       'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'EstimatedSalary'],
      dtype='object')

In [9]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
# X[:,2] = le.fit_transform(X[:,2])
X['Gender'] = le.fit_transform(X['Gender'])

In [10]:
X.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,619,France,0,42,2,0.00,1,1,1,101348.88
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58
2,502,France,0,42,8,159660.80,3,1,0,113931.57
3,699,France,0,39,1,0.00,2,0,0,93826.63
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10


In [11]:
import numpy as np
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])],remainder='passthrough')
X = np.array(ct.fit_transform(X))


In [12]:
X

array([[1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]], shape=(10000, 12))

In [13]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

In [14]:
X

array([[ 0.99720391, -0.57873591, -0.57380915, ...,  0.64609167,
         0.97024255,  0.02188649],
       [-1.00280393, -0.57873591,  1.74273971, ..., -1.54776799,
         0.97024255,  0.21653375],
       [ 0.99720391, -0.57873591, -0.57380915, ...,  0.64609167,
        -1.03067011,  0.2406869 ],
       ...,
       [ 0.99720391, -0.57873591, -0.57380915, ..., -1.54776799,
         0.97024255, -1.00864308],
       [-1.00280393,  1.72790383, -0.57380915, ...,  0.64609167,
        -1.03067011, -0.12523071],
       [ 0.99720391, -0.57873591, -0.57380915, ...,  0.64609167,
        -1.03067011, -1.07636976]], shape=(10000, 12))

In [15]:
from sklearn.model_selection import train_test_split
X_train,X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=0)


In [16]:
print("X Train = ",X_train.shape)
print("X Test = ",X_test.shape)
print("Y Train = ",y_train.shape)
print("Y Test = ",y_test.shape)

X Train =  (8000, 12)
X Test =  (2000, 12)
Y Train =  (8000,)
Y Test =  (2000,)


# ANN Model Building Architecture

In [17]:
ann = tf.keras.models.Sequential() # establish layer one after another 

In [18]:
ann.add(tf.keras.layers.Dense(units=6)) # input layer, densly connect layers to neurons (6 neurons)

In [19]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu')) # hidden layer 1

In [20]:
# ann.add(tf.keras.layers.Dense(units=6, activation='relu')) # hidden layer 2

In [21]:
# ann.add(tf.keras.layers.Dense(units=6, activation='relu')) # hidden layer 3

In [22]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid')) # output layer 1

In [23]:
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [24]:
ann.fit(X_train,y_train,batch_size=32,epochs=100) # taking 32 records as one batch and epochs for 10 times

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 467us/step - accuracy: 0.6465 - loss: 0.6839
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 381us/step - accuracy: 0.7954 - loss: 0.4955
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 381us/step - accuracy: 0.7990 - loss: 0.4449
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 383us/step - accuracy: 0.8015 - loss: 0.4305
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 376us/step - accuracy: 0.8076 - loss: 0.4250
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 380us/step - accuracy: 0.8130 - loss: 0.4208
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 382us/step - accuracy: 0.8173 - loss: 0.4161
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 378us/step - accuracy: 0.8201 - loss: 0.4110
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 377us/step - accuracy: 0.8236 - loss: 0.4057
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 377us/step - accuracy: 0.8246 - loss: 0.3989
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 385us/step - accuracy: 0.8281 - loss: 0.3920
Epoch 12/100
250/25

In [25]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)

# Ensure y_test is a numpy array and reshape both to 2D column vectors
y_pred_reshaped = np.array(y_pred).reshape(-1, 1)
y_test_reshaped = np.array(y_test).reshape(-1, 1)

# Concatenate side-by-side: [Predicted, Actual]
comparison = np.concatenate((y_pred_reshaped, y_test_reshaped), axis=1)

# Print first 10 rows to inspect
print("Predicted | Actual")
print(comparison[:10])

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 519us/step
Predicted | Actual
[[0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [1 1]]


In [26]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
print(cm)

[[1535   60]
 [ 213  192]]


In [27]:
from sklearn.metrics import accuracy_score
ac = accuracy_score(y_test,y_pred)
print(ac)

0.8635
